stages:
  - build
  - deploy

build frontend:
  stage: build
  only:
    refs:
      - main
  tags:
    - main
  script:
    - docker build -t frontend ./
deploy frontend:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - main
  script:
    - cd /opt/lyhike-nimi/frontend
    - docker-compose down
    - docker-compose up -d
